version: '3.5'
services:
    datahole:
        build:
            context: .
            dockerfile: ./Dockerfile 
        image: datahole
        ports:
            - 8090:80
        logging:
            driver: "json-file"
            options:
                max-size: 10m
                max-file: "3"
                env: "os"
                